spring:
  application:
    name: ms-pims-inventory-service
  service:
    name: ${spring.application.name}

  config:
    import: optional:configserver:http://fs-devops-configserver-svc.devops:8888
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
